---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: alicloud-disk-essd
parameters:
  type: cloud_essd
provisioner: diskplugin.csi.alibabacloud.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  name: data-elasticsearch-master-0
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: cn-hangzhou-i-cloud-efficiency-addon-sc
  volumeMode: Filesystem
  volumeName: disk-3483062e-261d-4dee-859d-b7528c16a57e
---
volumeClaimTemplates:
  - metadata:
      name: prometheus-prometheus-operator-prometheus-db
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: cn-hangzhou-i-cloud-efficiency-addon-sc
      volumeMode: Filesystem
---
volumeClaimTemplates:
  - metadata:
      name: database-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: aliyun-cloud-efficiency
      volumeMode: Filesystem
